apiVersion: v1
kind: ConfigMap
metadata:
  name: taskflow-config
  namespace: happyotter-dev
  labels:
    app: taskflow
data:
  ENVIRONMENT: "staging"
  USE_DATABASE: "false"
  LOG_LEVEL: "INFO"
  APP_VERSION: "1.0"